apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  ports:
    - port: 80
  selector:
    app: wordpress
    client: nokia
    tier: frontend
    type: testing
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
    client: nokia
    type: frontend
    server_type: testing
spec:
  selector:
    matchLabels:
      octopusexport: OctopusExport
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  template:
    metadata:
      labels:
        app: wordpress
        client: nokia
        tier: frontend
        type: testing
    spec:
      containers:
        - name: wordpress
          image: wordpress
          ports:
          - containerPort: 80
          resources:
            limits: 
              memory: 128Mi
              cpu: 200m